substitutions:
  device_name: multical402
  friendly_name: Multical 402
  sensor_name_prefix: Multical

esp8266:
  board: d1_mini

esphome:
  name: ${device_name}
  # No need to include files anymore as we're using a proper component

external_components:
  - source: github://0x414c49/esphome_multical402@main
    components: [multical402]  

### this is for local development
#external_components:
#  - source: components
#    components: [multical402]      

# Enable features
ota:
  - platform: esphome
    password: !secret ota_password

api:
  encryption: 
    key: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: False

logger:

# Define UART for the Multical 402
uart:
  id: uart_bus
  rx_pin: D1
  tx_pin: D2
  baud_rate: 1200
  data_bits: 8
  parity: NONE
  stop_bits: 1

# Use the external component
multical402:
  id: multical_meter
  update_interval: 10s

  energy:
    name: "${sensor_name_prefix} Energy Heat"
    icon: "mdi:lightning-bolt"
    unit_of_measurement: GJ
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
      
  volume:
    name: "${sensor_name_prefix} Volume"
    unit_of_measurement: m3
    accuracy_decimals: 2
    state_class: "measurement"

  temperature_in:
    name: "${sensor_name_prefix} Temperature In"
    icon: "mdi:thermometer"
    unit_of_measurement: °C
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "temperature"

  temperature_out:
    name: "${sensor_name_prefix} Temperature Out"
    icon: "mdi:thermometer"
    unit_of_measurement: °C
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "temperature"

  temperature_diff:
    name: "${sensor_name_prefix} Temperature Diff"
    icon: "mdi:thermometer"
    unit_of_measurement: °C
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "temperature"

  power:
    name: "${sensor_name_prefix} Power"
    icon: "mdi:flash"
    unit_of_measurement: kW
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "power"

  flow:
    name: "${sensor_name_prefix} Flow"
    unit_of_measurement: l/h
    accuracy_decimals: 0
    state_class: "measurement"